using System;
using System.Collections.Generic;

namespace Unity.Robotics
{
    // Which printed ArUco dictionary the calibration tag came from. These are OpenCV's
    // predefined dictionaries, so a tag generated by cv2.aruco, by aruco_ros, or by one of the
    // online marker generators decodes here without conversion.
    //
    // Prefer a dictionary with FEW markers for calibration: 4x4_50 tolerates one wrong bit,
    // 4x4_250 packs 250 codes into the same 16 bits and so tolerates the same single error
    // across five times as many neighbours. A bigger grid (6x6_250) is the robust choice when
    // the tag can be printed large enough to resolve 36 cells across the room.
    public enum ArucoDictionaryName
    {
        // 50 markers of 4x4 bits, corrects up to 1 wrong bit(s)
        Dict4x4_50,
        // 250 markers of 4x4 bits, corrects up to 1 wrong bit(s)
        Dict4x4_250,
        // 250 markers of 5x5 bits, corrects up to 2 wrong bit(s)
        Dict5x5_250,
        // 250 markers of 6x6 bits, corrects up to 5 wrong bit(s)
        Dict6x6_250,
    }

    // The marker code tables for the supported OpenCV dictionaries, plus the lookup that turns
    // an observed grid of bits back into a marker id and orientation.
    //
    // The tables below are DATA, not something derivable: OpenCV's predefined dictionaries are
    // pseudo-random code sets chosen to maximise inter-marker Hamming distance, so there is no
    // formula to regenerate them from. They were dumped from opencv-contrib 5.0.0 and every
    // entry was verified against what cv2.aruco.generateImageMarker actually draws for that id -
    // which is the check that matters, because the printed tag is the ground truth, not the byte
    // table. Regenerating them by hand is not a thing to attempt; a single wrong entry shows up
    // only as a tag that never decodes.
    //
    // Bit convention: row-major, MSB first, starting at the marker's top-left cell as printed.
    // A 1 bit is a WHITE cell (which is how OpenCV renders them). The black quiet border around
    // the grid is not part of the code - it is what the detector uses to reject candidates.
    public sealed class ArucoDictionary
    {
        // OpenCV DICT_4X4_50 - 50 markers of 4x4 bits
        private static readonly ulong[] k_Dict4x4_50 =
        {
            0xB532, 0xF9A, 0x332D, 0x9946, 0x549E, 0x79CD, 0x9E2E, 0xC4F2, 0xFEDA, 0xCF56,
            0xF991, 0x11A7, 0xEB7, 0x2A0F, 0x24B1, 0x263E, 0x4665, 0x6600, 0x6C5E, 0x76AF,
            0x868B, 0xB02B, 0xCCD5, 0xDD82, 0xFE47, 0x9471, 0xACE4, 0xA554, 0x2123, 0x346F,
            0x4415, 0x57B2, 0x9ECF, 0xF0CB, 0x8AE, 0x929, 0x1875, 0x4FF, 0xDF6, 0x1C5A,
            0x1718, 0x2A28, 0x328C, 0x38B2, 0x24E8, 0x2EEB, 0x2D3F, 0x4B64, 0x502E, 0x5013
        };

        // OpenCV DICT_4X4_250 - 250 markers of 4x4 bits
        private static readonly ulong[] k_Dict4x4_250 =
        {
            0xB532, 0xF9A, 0x332D, 0x9946, 0x549E, 0x79CD, 0x9E2E, 0xC4F2, 0xFEDA, 0xCF56,
            0xF991, 0x11A7, 0xEB7, 0x2A0F, 0x24B1, 0x263E, 0x4665, 0x6600, 0x6C5E, 0x76AF,
            0x868B, 0xB02B, 0xCCD5, 0xDD82, 0xFE47, 0x9471, 0xACE4, 0xA554, 0x2123, 0x346F,
            0x4415, 0x57B2, 0x9ECF, 0xF0CB, 0x8AE, 0x929, 0x1875, 0x4FF, 0xDF6, 0x1C5A,
            0x1718, 0x2A28, 0x328C, 0x38B2, 0x24E8, 0x2EEB, 0x2D3F, 0x4B64, 0x502E, 0x5013,
            0x5194, 0x5568, 0x5D41, 0x5F97, 0x6801, 0x6867, 0x6124, 0x61E9, 0x6B12, 0x6FE5,
            0x67DF, 0x7E1B, 0x80A0, 0x8344, 0x8BA2, 0x937A, 0x846C, 0x852A, 0x859C, 0x9C89,
            0x9FA1, 0xBB7C, 0xBC04, 0xB65B, 0xBFC8, 0xB7AB, 0xCA1F, 0xC962, 0xD958, 0xD3D5,
            0xCC98, 0xC7A0, 0xC537, 0xE95D, 0xF925, 0xFBBB, 0xEE2A, 0xF74D, 0x3575, 0x8AAD,
            0x7617, 0xACF, 0x64B, 0x2DC1, 0x49D8, 0x43F4, 0x4F36, 0x4FD3, 0x69E4, 0x70C7,
            0x7A6E, 0xB4EA, 0xED4F, 0xFCE7, 0xFEA6, 0x25, 0x43, 0xA88, 0xA86, 0x26F,
            0x1C, 0x97, 0x837, 0xA31, 0x9C6, 0xB01, 0x9FB, 0xB58, 0x1082, 0x182D,
            0x1078, 0x1073, 0x1274, 0x12B1, 0x1AF9, 0x1306, 0xC0E, 0xCF1, 0x433, 0xC9F,
            0xEF2, 0xEFD, 0x74C, 0xFA4, 0x72F, 0x5B5, 0xF91, 0x7DB, 0x1EE4, 0x1439,
            0x1D80, 0x15C8, 0x1F8B, 0x15BA, 0x1DB1, 0x2080, 0x28E9, 0x22A2, 0x2853, 0x2AF0,
            0x22F7, 0x2940, 0x2146, 0x29B9, 0x2B9C, 0x2BB2, 0x38CA, 0x382E, 0x3007, 0x38E7,
            0x3A49, 0x3A65, 0x325D, 0x3B88, 0x391D, 0x3BD3, 0x2647, 0x2780, 0x2FAA, 0x2D14,
            0x25DE, 0x2553, 0x2F77, 0x3448, 0x3CA8, 0x3C41, 0x340D, 0x34FB, 0x369A, 0x3DE0,
            0x356A, 0x3D09, 0x3DED, 0x3FC4, 0x3F6C, 0x37CE, 0x3D5C, 0x3D76, 0x37B0, 0x3F17,
            0x3FFF, 0x48E5, 0x4268, 0x4A2D, 0x4160, 0x4951, 0x41DD, 0x4BDF, 0x584F, 0x5A48,
            0x5816, 0x505D, 0x5AFA, 0x5AB5, 0x5123, 0x5B8A, 0x5919, 0x5135, 0x4C69, 0x46C1,
            0x4E0B, 0x445F, 0x4E59, 0x4D83, 0x4D7D, 0x47D8, 0x4773, 0x5C85, 0x5E44, 0x562B,
            0x5CBB, 0x55C3, 0x5F6E, 0x5FEB, 0x5D12, 0x555E, 0x6270, 0x6215, 0x61C2, 0x6B20,
            0x6345, 0x6B5C, 0x6B5B, 0x780C, 0x7ACF, 0x787F, 0x7980, 0x71E5, 0x7174, 0x79B6,
            0x71D3, 0x7B33, 0x646A, 0x66A8, 0x6EA7, 0x6E91, 0x6522, 0x6DCB, 0x678D, 0x6D31
        };

        // OpenCV DICT_5X5_250 - 250 markers of 5x5 bits
        private static readonly ulong[] k_Dict5x5_250 =
        {
            0x145B2BC, 0x1C06E6, 0x1AF0EDD, 0x10395F7, 0x1AEB524, 0x1D4082D, 0xD3D7EC, 0xE2146B, 0x10D6132, 0x1313FA5,
            0x13CEE03, 0x1A2DAC0, 0x1E62B11, 0x5E7166, 0x1FCFCA8, 0x51E37F, 0x97A758, 0xBEA26F, 0xF64DC4, 0x1061DE8,
            0x12DDA75, 0x150E440, 0x16B0CA1, 0xBA12DE, 0x19CD023, 0x1A59972, 0x1C3CE8B, 0x224246, 0x3B9672, 0x24223B,
            0x27376E, 0x368873, 0x40D0CE, 0x4AAAC8, 0x4643BA, 0x7A6FEA, 0x998AAC, 0x82D101, 0x9AAD1D, 0x863C72,
            0xAD2825, 0xA52F9E, 0xD849F7, 0xC309D9, 0xDA7E31, 0xE9627A, 0xE9B997, 0xF94806, 0xF59125, 0xF6B7D7,
            0x11B58E4, 0x11AD279, 0x11E380B, 0x1169445, 0x12FFB4A, 0x158CB8D, 0x15987F0, 0x1422FDF, 0x14E1227, 0x156DF22,
            0x173DBF1, 0x164C93C, 0x17CBB86, 0x1880A87, 0x19147DD, 0x184EB8A, 0x18D85AD, 0x1B2CDA9, 0x1BABD73, 0x1E9D432,
            0x1E76528, 0xF5740A, 0x1B11A53, 0x18CE65, 0x2AB219, 0x98E981, 0xA8061C, 0x141A158, 0x185314C, 0x196D12C,
            0x1FAD3A2, 0x922B5, 0x19BCE0, 0xB547C, 0x2C76F, 0x132289, 0x12D2A7, 0xC4B43, 0x67BC5, 0xFAA0D,
            0x1F1F54, 0x38E879, 0x323B23, 0x2C3647, 0x2DA51B, 0x2E9D8D, 0x27C562, 0x3EFDF5, 0x521EE0, 0x448EFD,
            0x542F81, 0x55F6C9, 0x47E008, 0x4F9BF8, 0x46D558, 0x5EF65E, 0x692188, 0x6013AD, 0x68BC21, 0x72A5D0,
            0x6400E2, 0x6DCE3A, 0x891409, 0x89D9FD, 0x8A3EE5, 0x8A952A, 0x8C277D, 0x9D0612, 0x8EE533, 0x9F04FB,
            0xB86F1B, 0xB1FAEE, 0xA36FF0, 0xB275F6, 0xB53332, 0xA603E1, 0xA798CF, 0xA6DC02, 0xB64B5F, 0xBFAB99,
            0xCACC85, 0xCB8F5E, 0xCC6EA2, 0xCE198B, 0xE12CBB, 0xF8C701, 0xF35752, 0xE47A8C, 0xE7CB65, 0x1084D18,
            0x113E202, 0x10D5DD3, 0x11447F3, 0x1286AE3, 0x1388A36, 0x12A3F49, 0x12D1B20, 0x12E4D6E, 0x1366ECE, 0x1378DC1,
            0x14134DD, 0x148A50D, 0x151610B, 0x15B3684, 0x15FE0B1, 0x1605CC7, 0x1601E30, 0x179D565, 0x17D8899, 0x16705F4,
            0x166B079, 0x17E8BDC, 0x17EAC67, 0x18875E0, 0x199D306, 0x18A6601, 0x19A44C7, 0x18C1115, 0x18D287E, 0x195DD09,
            0x19F4E25, 0x196C3C5, 0x1A005D2, 0x1B96E8C, 0x1B31709, 0x1B39D64, 0x1A53281, 0x1A5A22E, 0x1BCB4DD, 0x1B48E85,
            0x1B67820, 0x1B71F92, 0x1D031C7, 0x1CA38DE, 0x1C35C71, 0x1DB72F7, 0x1D3C064, 0x1D6BA18, 0x1DFF33A, 0x1F02202,
            0x1F00FA6, 0x1EC0441, 0x1EC36BF, 0x1FD6BDA, 0x1F46671, 0x1F49583, 0x1EE5EE1, 0x1EFD5F9, 0x1FE3129, 0x1F746BC,
            0xD1705E, 0x1321E17, 0x133B04D, 0x1C8BE1D, 0x3A20DD, 0x558261, 0x6882C7, 0x6F80E9, 0x7E6B97, 0xAD4098,
            0xAE7073, 0xCD3170, 0xE74A2E, 0xFE59FB, 0x1168FD2, 0x14B872E, 0x15353D6, 0x16A336E, 0x165B533, 0x18983E8,
            0x195723C, 0x1B0DF47, 0x1BF1B1C, 0x1CACD1F, 0x1DA8E35, 0x1E0CF0D, 0x853DD, 0x468F, 0x145F6, 0x9919C,
            0x1A5C3, 0x18141E, 0x11178C, 0x190CB6, 0xB03FA, 0x2E23C, 0x3842B, 0x3CEE2, 0x12537E, 0x1A2037,
            0x1A0A30, 0x1BDA5F, 0x1ACDBC, 0x13E4EC, 0x5A105, 0x4C592, 0xDE752, 0xDDE46, 0x1C7C24, 0x1535BB
        };

        // OpenCV DICT_6X6_250 - 250 markers of 6x6 bits
        private static readonly ulong[] k_Dict6x6_250 =
        {
            0x1E3DD82A6, 0xEFBA3891, 0x15907EACD, 0xC91B3069E, 0xD607D6E15, 0xD8E8E0E68, 0x4268B41F5, 0x88A50F29A, 0x307D524FD, 0x3C2F34B3C,
            0x45DFC74E3, 0x48D85B257, 0x710558FC6, 0x86DCFAD07, 0x8D72A93F6, 0xA2B89DCDE, 0x9FD1E9C4, 0x154DBD18F, 0x300A310E2, 0x4807EFAFD,
            0x56DF11DB6, 0x66883274C, 0x76E8CB781, 0x9A53D9CF3, 0xA9CB84024, 0xC67549490, 0xC1D288941, 0xE7480852B, 0xEA2FCA848, 0xE963B77B1,
            0xFA36652AF, 0x65BFF7BD, 0x541D72D6, 0xCF7246A2, 0x1338A39EB, 0x15A893E74, 0x3A417EE9E, 0x4F11E26C0, 0x530DB6D20, 0x589BFAE34,
            0x6409E8A0B, 0x60537A891, 0x6159069BA, 0x6BFF78D7B, 0x70AD96A4F, 0x75846F71A, 0x7A95192FC, 0x8609760AA, 0x8A2D44C3F, 0x93EB78B14,
            0x988DA84D4, 0x9EDE2B3C8, 0xA529E07B8, 0xB593B855F, 0xB7F8E426F, 0xBC205225E, 0xC04487765, 0xC4C324259, 0xC5A91BD8D, 0xCE73E6B2C,
            0xCD0CA6272, 0xC9435D44D, 0xCFBE80F34, 0xE57D15877, 0xEFC6858E9, 0xF77EF3772, 0x2CE43F254, 0x2BDCFF4B3, 0x37C7DDBDA, 0xA1A254E0F,
            0xA982C1BB5, 0xD81B49B08, 0x35829F86, 0x7C4095FC, 0xFE26617B, 0x144836441, 0x10AD5FFB7, 0x12829553F, 0x16E13184C, 0x187A496B0,
            0x1AE886112, 0x1913AE0A1, 0x1B67B5A17, 0x25DC95F0B, 0x288961F76, 0x3354146AA, 0x31C16C1F7, 0x33CB18C66, 0x3ECFE490F, 0x464518A3F,
            0x44BA70B67, 0x419C623E8, 0x48D1914A1, 0x54F499F6D, 0x575A9C813, 0x558355B2C, 0x57B77610F, 0x5C3436FE4, 0x5C48FC77E, 0x5E6EEF402,
            0x5F233B6FF, 0x5B742A632, 0x650FA33AE, 0x65D3175CC, 0x6A9C245AE, 0x69C5F3042, 0x69D2484EA, 0x7479E2DE6, 0x72CF23EAB, 0x77B1DC414,
            0x7E0C07217, 0x7A6970647, 0x78B2D8707, 0x79C585794, 0x866F59FC6, 0x82F6727F5, 0x854E2F414, 0x9A1185934, 0x9C7160C97, 0x9DD194FD8,
            0xA21E12E38, 0xAE701C82C, 0xAD01219C1, 0xB0351F9EE, 0xB64AD80D4, 0xB537314B4, 0xBEAAC7E3B, 0xBB683DBCF, 0xC672F72C1, 0xC1E74DBAB,
            0xCB55EE59D, 0xCBA053724, 0xD0090FCF1, 0xD06C3AD54, 0xD3F120574, 0xE6E33B1A7, 0xE3533EA4A, 0xE8068EB14, 0xEC07C0597, 0xEAF3803DA,
            0xF63B27D88, 0xF30798379, 0xFE4BBA9B9, 0xABA57D86B, 0xC0D1625AB, 0x13CE7BAE7, 0x4E81FD617, 0x56E076320, 0x6A708A540, 0x72A898A18,
            0x815D42F80, 0xCF4CC3D5F, 0xD6BB65864, 0xECD313A31, 0xF521F5207, 0xF91FA5DF7, 0x24F47A7, 0x84D882, 0x43CC2F29, 0x47B50211,
            0x67AE4C1D, 0xAA968A3, 0x4D138E94, 0x510A80DA, 0x140B0007, 0x19D9CEE1, 0x81057E3B, 0x86B97B66, 0xEE8B860A, 0xB6C76B9B,
            0xFDCB98CB, 0xFCACF3A0, 0x14249FD98, 0x1407201FD, 0x150910D57, 0x135CD7307, 0x11479ABB6, 0x1CB9A9238, 0x1CDD07766, 0x1F2E7C24B,
            0x196642477, 0x1957D4C84, 0x1FA8F4F04, 0x1B8246ED8, 0x1BAEE10FE, 0x22A4B63CA, 0x22BF9012F, 0x232C15B40, 0x255AA966C, 0x27A5AFA97,
            0x25F40E425, 0x286655CDE, 0x2C427E0E0, 0x2AB97CBD0, 0x2946E1D23, 0x2DA628410, 0x2BFB209A6, 0x368CD66BC, 0x3487777C7, 0x34DDEB840,
            0x3791F76F1, 0x3A228E175, 0x3E13BD408, 0x3C9843CA2, 0x39589D179, 0x3974DAEEB, 0x3F6DBC731, 0x3D6BC050C, 0x39AB27497, 0x46024E25E,
            0x4682BA0BC, 0x42E9CD5AE, 0x44C9B7B3F, 0x40C7D41E9, 0x46D2B4CCE, 0x43195356B, 0x4122E6DD9, 0x4753A59AB, 0x4E1EF1E08, 0x4E4AC0960,
            0x4E5FAA06F, 0x4A8D32943, 0x491594B39, 0x4D4DDB621, 0x4BA761E81, 0x49D483D8E, 0x56290EF6C, 0x537ED5FFC, 0x55F5A7AFA, 0x55D5EA64F,
            0x581BAB1DA, 0x5EBE926DD, 0x5F10F99B5, 0x5D1EDFA5C, 0x5F718DF02, 0x5DE11E468, 0x6033BB247, 0x64581AFE1, 0x63C8DDA76, 0x61DA3D8FD,
            0x6E3A22AFA, 0x6E6105B71, 0x6A89A9E8C, 0x6A97224F5, 0x6B12C3801, 0x6B684B22A, 0x6F94C1579, 0x6DA6FEA0D, 0x6FEACA457, 0x703D38A60
        };

        private readonly ulong[] _codes;

        // All four 90-degree rotations of every code, laid out as [id * 4 + rotation]. Built
        // once per dictionary: identification has to try every rotation of every marker for each
        // candidate, because a printed tag can be approached from any side.
        private readonly ulong[] _rotatedCodes;

        private static readonly Dictionary<ArucoDictionaryName, ArucoDictionary> k_Cache =
            new Dictionary<ArucoDictionaryName, ArucoDictionary>();

        public ArucoDictionaryName Name { get; }

        // Cells per side of the code grid, excluding the black border (4 for a 4x4 dictionary)
        public int GridSize { get; }

        // How many wrong bits a candidate may have and still be accepted as a given id. This is
        // OpenCV's own maxCorrectionBits for the dictionary: (minimum inter-marker distance - 1)
        // / 2, the largest budget that still cannot turn one valid marker into a different one.
        public int MaxCorrectionBits { get; }

        public int MarkerCount => _codes.Length;

        public int BitCount => GridSize * GridSize;

        private ArucoDictionary(ArucoDictionaryName name, int gridSize, int maxCorrectionBits,
            ulong[] codes)
        {
            Name = name;
            GridSize = gridSize;
            MaxCorrectionBits = maxCorrectionBits;
            _codes = codes;

            _rotatedCodes = new ulong[codes.Length * 4];
            for (int id = 0; id < codes.Length; id++)
            {
                ulong code = codes[id];
                for (int rotation = 0; rotation < 4; rotation++)
                {
                    _rotatedCodes[id * 4 + rotation] = code;
                    code = RotateClockwise(code, gridSize);
                }
            }
        }

        public static ArucoDictionary Get(ArucoDictionaryName name)
        {
            if (k_Cache.TryGetValue(name, out var cached))
                return cached;

            ArucoDictionary dictionary;
            switch (name)
            {
                case ArucoDictionaryName.Dict4x4_50:
                    dictionary = new ArucoDictionary(name, 4, 1, k_Dict4x4_50);
                    break;
                case ArucoDictionaryName.Dict4x4_250:
                    dictionary = new ArucoDictionary(name, 4, 1, k_Dict4x4_250);
                    break;
                case ArucoDictionaryName.Dict5x5_250:
                    dictionary = new ArucoDictionary(name, 5, 2, k_Dict5x5_250);
                    break;
                case ArucoDictionaryName.Dict6x6_250:
                    dictionary = new ArucoDictionary(name, 6, 5, k_Dict6x6_250);
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(name), name,
                        "Unknown ArUco dictionary");
            }

            k_Cache[name] = dictionary;
            return dictionary;
        }

        // The canonical code for an id, for drawing a printable tag
        public ulong GetCode(int id)
        {
            if (id < 0 || id >= _codes.Length)
                throw new ArgumentOutOfRangeException(nameof(id), id,
                    $"{Name} has ids 0..{_codes.Length - 1}");
            return _codes[id];
        }

        public bool IsBitSet(ulong code, int row, int column)
        {
            int shift = BitCount - 1 - (row * GridSize + column);
            return ((code >> shift) & 1UL) != 0UL;
        }

        // Turn an observed grid of bits into a marker id.
        //
        // `rotation` is how many 90-degree CLOCKWISE turns of the observed grid line it up with
        // the printed one, which is also what tells the caller which observed corner is the
        // marker's top-left: canonical corner j is observed corner (j - rotation) mod 4, for
        // corners listed clockwise in image space. Without that the id would be right while the
        // pose came out yawed by a multiple of 90 degrees - the classic way a marker-based
        // calibration ends up placing a robot sideways.
        public bool TryIdentify(ulong observed, out int id, out int rotation, out int errors)
        {
            id = -1;
            rotation = 0;
            errors = int.MaxValue;

            for (int candidate = 0; candidate < _codes.Length; candidate++)
            {
                for (int turn = 0; turn < 4; turn++)
                {
                    int distance = HammingDistance(observed, _rotatedCodes[candidate * 4 + turn]);
                    if (distance >= errors)
                        continue;

                    errors = distance;
                    id = candidate;
                    // _rotatedCodes[id * 4 + turn] is the printed code turned CW `turn` times,
                    // and it matched what we saw - so turning what we saw CW (4 - turn) times
                    // gets back to the printed orientation.
                    rotation = (4 - turn) & 3;

                    if (distance == 0)
                        return true;
                }
            }

            if (errors > MaxCorrectionBits)
            {
                id = -1;
                rotation = 0;
                errors = int.MaxValue;
                return false;
            }

            return true;
        }

        // 90 degrees clockwise: the cell at (row, column) moves to (column, GridSize - 1 - row)
        public static ulong RotateClockwise(ulong code, int gridSize)
        {
            int bits = gridSize * gridSize;
            ulong result = 0UL;
            for (int row = 0; row < gridSize; row++)
            {
                for (int column = 0; column < gridSize; column++)
                {
                    int sourceShift = bits - 1 - (row * gridSize + column);
                    if (((code >> sourceShift) & 1UL) == 0UL)
                        continue;

                    int destinationShift = bits - 1 - (column * gridSize + (gridSize - 1 - row));
                    result |= 1UL << destinationShift;
                }
            }
            return result;
        }

        // Mirrored left-to-right: the cell at (row, column) moves to (row, GridSize - 1 - column)
        public static ulong MirrorHorizontal(ulong code, int gridSize)
        {
            int bits = gridSize * gridSize;
            ulong result = 0UL;
            for (int row = 0; row < gridSize; row++)
            {
                for (int column = 0; column < gridSize; column++)
                {
                    int sourceShift = bits - 1 - (row * gridSize + column);
                    if (((code >> sourceShift) & 1UL) == 0UL)
                        continue;

                    int destinationShift = bits - 1 - (row * gridSize + (gridSize - 1 - column));
                    result |= 1UL << destinationShift;
                }
            }
            return result;
        }

        // DIAGNOSIS ONLY - never a route to accepting a marker.
        //
        // TryIdentify searches the four ROTATIONS, because that is the only ambiguity a
        // correctly-oriented camera can produce. A vertically flipped image is a REFLECTION,
        // which no amount of rotation reaches, so every tag in a mirrored feed decodes as
        // nothing at all. Downstream that is indistinguishable from a tag printed from the
        // wrong dictionary, and it sends the user off to reprint a tag that was fine.
        //
        // A mirrored pose would be wrong in a way nothing later could detect, so this answers
        // the diagnostic question only: would this code have been a tag, had the image not been
        // reflected? The caller reports that and stops.
        public bool IdentifiesWhenMirrored(ulong observed)
        {
            ulong mirrored = MirrorHorizontal(observed, GridSize);
            return TryIdentify(mirrored, out _, out _, out _);
        }

        private static int HammingDistance(ulong a, ulong b)
        {
            ulong diff = a ^ b;
            int count = 0;
            while (diff != 0UL)
            {
                diff &= diff - 1UL;
                count++;
            }
            return count;
        }
    }
}
