#pragma kernel PointCloudReconstructionGPU

// Input frames
Texture2D<float4> inColor;
Texture2D<float4> inDepth;

// Output frame
RWStructuredBuffer<float4> colorOut;
RWStructuredBuffer<float3> depthOut;
RWStructuredBuffer<float> distanceToOrigin;

// Depth Camera Intrinsics Info
float4 camInfoDepth;

int colorImageWidth;
int colorImageHeight;

float4x4 originTransform;

[numthreads(8,8,1)]
void PointCloudReconstructionGPU (uint3 id : SV_DispatchThreadID)
{
    uint pixelID = (id.y * colorImageWidth + id.x);
    
    // Convert normalized depth back to actual depth in meters (assuming depth is in millimeters and normalized to [0,1])
    float depthNorm = inDepth.Load(int3(id.x, id.y, 0));
    float depth = depthNorm * 65535.0 * 0.001; 
    
    if(depth > 0)
    {
        float y = depth ; // Unity's Y is FLU's Z
        float z = ((id.x - camInfoDepth[0]) * depth / camInfoDepth[2]); // Unity's Z is FLU's X
        float x = (-(id.y - camInfoDepth[1]) * depth / camInfoDepth[3]); // Unity's X is FLU's -Y

        int colColor = (int)id.x;
        int rowColor = (int)id.y;

        distanceToOrigin[pixelID] = float(y);

        if(colColor >= 0 && colColor < colorImageWidth && rowColor >= 0 && rowColor < colorImageHeight)
        {
            colorOut[pixelID] = inColor[int2(colColor,rowColor)];
        } 

        float4x4 pointInCam = {1,0,0,x,0,1,0,y,0,0,1,z,1,1,1,1};
        float4x4 pointInWorld = mul(originTransform,pointInCam);

        x = pointInWorld[0][3];
        y = pointInWorld[1][3];
        z = pointInWorld[2][3];

        depthOut[pixelID] = float3(x,y,z);
    } 
    else
    {
        depthOut[pixelID] = float3(0,0,0);
        colorOut[pixelID] = float4(1,1,1,0);
        distanceToOrigin[pixelID] = float(0);
    }
}